#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Combine must be used with at least 2 arguments" 1>&2
    exit 1
fi

if [ -e $1 ]; then
   echo "Error: first file exists" 1>&2
   exit 1
fi

filename=$1

touch "$filename"

shift

while (( "$#" )); do

    if [ -e $1 ]; then
	cat "$1"
    else
	echo "$1 file was not found" > "$filename"
    fi

shift

done
